package com.services;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * XacmlserviceService service = new XacmlserviceService();
 * XacmlserviceDelegate portType = service.getXacmlservicePort();
 * portType.getFile(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "XacmlserviceService", targetNamespace = "http://webservices.com/", wsdlLocation = "http://localhost:8081/XacmlServices/XacmlservicePort?wsdl")
public class XacmlserviceService extends Service {

	private final static URL XACMLSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.services.XacmlserviceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.services.XacmlserviceService.class.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8081/XacmlServices/XacmlservicePort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/XacmlServices/XacmlservicePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		XACMLSERVICESERVICE_WSDL_LOCATION = url;
	}

	public XacmlserviceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public XacmlserviceService() {
		super(XACMLSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://webservices.com/", "XacmlserviceService"));
	}

	/**
	 * 
	 * @return returns XacmlserviceDelegate
	 */
	@WebEndpoint(name = "XacmlservicePort")
	public XacmlserviceDelegate getXacmlservicePort() {
		return super.getPort(new QName("http://webservices.com/",
				"XacmlservicePort"), XacmlserviceDelegate.class);
	}

}
